- hosts: app_node*
  tasks:
  - name: Install netcat
    yum:
      name: nc
      state: latest
    become: yes
    become_method: sudo
  - name: bash_httpd create service
    template:
      src: bash_httpd.service
      dest: /usr/lib/systemd/system/bash_httpd.service
      owner: root
      group: root
      mode: '0644'
    become: yes
    become_method: sudo
  - name: reload systemctl
    systemd:
      daemon_reload: yes
    become: yes
    become_method: sudo
  - name: bash_httpd start and enable
    systemd:
      name: bash_httpd
      state: started
      enabled: yes
    become: yes
    become_method: sudo
